apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-alpine
  name: my-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-alpine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-alpine
    spec:
      containers:
      - image: alpine:latest
        name: alpine
        resources: {}
status: {}
