apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-nodeport
  name: nginx-nodeport
spec:
  ports:
  - name: "http-port"
    port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30109
  selector:
    app: nginx-nodeport
  type: NodePort
